version: "3.4"

# DRY by YAML Anchors
# Reference: https://medium.com/@kinghuang/docker-compose-anchors-aliases-extensions-a1e4105d70bd.
x-: &app_base
  image: promo-php
  restart: always
  networks:
      - flm
  links:
      - "database"
  depends_on:
      - "database"
  build:
    context: ./
    dockerfile: ./docker/php/Dockerfile

services:
  web:
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 90:80
    restart: always
    networks:
      - flm
    depends_on:
      - php
  php:
    <<: *app_base
  database:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    env_file:
        - ".env"
    networks:
        - flm
    ports:
        - "8900:3306"
    volumes:
        - "./data/db/mysql:/var/lib/mysql"
    environment:
        MYSQL_DATABASE: app
        MYSQL_ROOT_PASSWORD: test
        MYSQL_USER: test
        MYSQL_PASSWORD: test
# Volumes
volumes:
  mysqldata:

networks:
  flm: